from fastapi import APIRouter, HTTPException, Depends
from app.api.deps import get_current_staff
from app.models.cart_model import get_cart, remove_cart, list_all_carts
from app.models.order_model import create_bill, create_order
from app.database.mongodb import get_database
from app.utils.pdf_service import save_invoice_pdf
from datetime import datetime, timezone
from pydantic import BaseModel
from bson import ObjectId
import uuid

router = APIRouter(prefix="/api/staff", tags=["Staff Billing"])


# ── Dashboard Summary ─────────────────────────────────────────
@router.get("/dashboard-summary")
async def staff_dashboard_summary(current_user: dict = Depends(get_current_staff)):
    """
    Returns live shift metrics for the logged-in staff member.
    Shift = current calendar day (UTC). Only 'Paid' bills count toward revenue.
    """
    db = get_database()
    staff_id = current_user["id"]

    # Day boundary in UTC
    today_start = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0)

    # DEBUG logs
    print(f"DEBUG: Fetching summary for Staff ID: {staff_id} ({current_user.get('name')})")
    print(f"DEBUG: Today Start (UTC): {today_start}")

    # Aggregate today's paid bills for this staff member
    pipeline = [
        {
            "$match": {
                "staff_id": staff_id,
                "payment_status": {"$in": ["Paid", "paid", "Completed", "completed"]},
                "created_at": {"$gte": today_start},
            }
        },
        {
            "$group": {
                "_id": None,
                "shift_revenue": {"$sum": "$total"},
                "transactions_count": {"$sum": 1},
            }
        },
    ]
    agg = await db["bills"].aggregate(pipeline).to_list(1)
    revenue_data = agg[0] if agg else {"shift_revenue": 0, "transactions_count": 0}

    shift_revenue = round(revenue_data["shift_revenue"], 2)
    txn_count = revenue_data["transactions_count"]
    avg_bill = round(shift_revenue / txn_count, 2) if txn_count > 0 else 0.0

    print(f"DEBUG: Found {txn_count} bills today. Shift Revenue: ₹{shift_revenue}")

    # Count all active carts (not staff-specific — carts are customer-owned)
    all_carts = await list_all_carts()
    active_carts = len(all_carts) if all_carts else 0

    # Count today's invoices generated by this staff (any payment status)
    today_invoices = await db["bills"].count_documents({
        "staff_id": staff_id,
        "created_at": {"$gte": today_start},
    })

    return {
        "shift_revenue": shift_revenue,
        "transactions_count": txn_count,
        "avg_bill": avg_bill,
        "successful_transactions_today": txn_count,
        "active_carts": active_carts,
        "today_invoices": today_invoices,
    }


class GenerateBillRequest(BaseModel):
    customer_id: str
    tax_rate: float = 0.05
    discount: float = 0.0
    payment_status: str = "Paid"


@router.post("/generate-bill")
async def staff_generate_bill(
    req: GenerateBillRequest,
    current_user: dict = Depends(get_current_staff)
):
    db = get_database()
    customer_id = req.customer_id

    # 1. Fetch cart
    cart = await get_cart(customer_id)
    if not cart or not cart.get("medicines"):
        raise HTTPException(status_code=400, detail="Cart is empty or does not exist")

    # 2. Validate stock and enrich medicine names
    enriched_items = []
    for item in cart["medicines"]:
        med_id = item["medicine_id"]
        # Safe ObjectId conversion
        try:
            med_id_obj = ObjectId(med_id) if isinstance(med_id, str) else med_id
            med = await db["medicines"].find_one({"_id": med_id_obj})
        except Exception as e:
            print(f"ERROR: Invalid medicine ID '{med_id}': {e}")
            raise HTTPException(status_code=400, detail=f"Invalid medicine identifier: {med_id}")

        if not med:
            print(f"ERROR: Medicine ID '{med_id}' not found in inventory.")
            raise HTTPException(status_code=404, detail=f"Medicine not found: {med_id}")
        
        if med["stock"] < item["quantity"]:
            raise HTTPException(
                status_code=400,
                detail=f"Insufficient stock for '{med['name']}'. Available: {med['stock']}, Requested: {item['quantity']}"
            )

        # Logic: Prioritize cart price, then med selling_price, then med price
        price = item.get("price") or med.get("selling_price") or med.get("price", 0)
        
        # Point-of-sale data (Expiry/Batch)
        expiry = med.get("expiry_date", med.get("expiry", "None"))
        batch = med.get("batch_number", med.get("batch", "NA"))

        enriched_items.append({
            "medicine_id": str(med_id),
            "medicine_name": med["name"],
            "price": price,
            "quantity": item["quantity"],
            "subtotal": round(price * item["quantity"], 2),
            "category": med.get("category", ""),
            "previous_stock": med["stock"],
            "expiry_date": expiry if expiry != "None" else "Not provided",
            "batch_number": batch if batch != "NA" else "General"
        })

    # 3. Calculate totals
    subtotal = round(sum(i["subtotal"] for i in enriched_items), 2)
    tax = round(subtotal * req.tax_rate, 2)
    discount = round(req.discount, 2)
    total = round(subtotal + tax - discount, 2)
    bill_id = str(uuid.uuid4())[:8].upper()

    # 4. Deduct stock and write inventory logs
    now = datetime.now(timezone.utc)
    for item in enriched_items:
        # Reduce medicine stock
        await db["medicines"].update_one(
            {"_id": ObjectId(item["medicine_id"])},
            {"$inc": {"stock": -item["quantity"]}}
        )
        
        # Write advanced inventory log
        from app.models.inventory_model import log_inventory_change
        await log_inventory_change({
            "medicine_id": item["medicine_id"],
            "medicine_name": item["medicine_name"],
            "type": "stock_out",
            "quantity": item["quantity"],
            "reason": "sale",
            "reference_id": bill_id,
            "performed_by": current_user["id"],
            "performed_by_name": current_user.get("name", "Staff"),
            "performed_by_role": "Staff",
            "previous_stock": item["previous_stock"],
            "updated_stock": item["previous_stock"] - item["quantity"],
            "created_at": now
        })

    # 5. Fetch customer name
    try:
        customer = await db["customers"].find_one({"_id": ObjectId(customer_id)})
        customer_name = customer["name"] if customer else "Unknown"
    except Exception:
        customer_name = "Unknown"

    # 6. Create bill document
    bill_data = {
        "bill_id": bill_id,
        "customer_id": customer_id,
        "customer_name": customer_name,
        "staff_id": current_user["id"],
        "staff_name": current_user.get("name", "Staff"),
        "medicines": enriched_items,
        "subtotal": subtotal,
        "tax": tax,
        "tax_rate": req.tax_rate,
        "discount": discount,
        "total": total,
        "payment_status": req.payment_status,
        "created_at": now,
    }
    new_bill = await create_bill(bill_data)
    
    # 6.5 Generate and Save PDF Invoice
    try:
        invoice_url = save_invoice_pdf(new_bill)
        # Update bill with invoice_url
        await db["bills"].update_one(
            {"_id": ObjectId(new_bill["id"])},
            {"$set": {"invoice_url": invoice_url}}
        )
        new_bill["invoice_url"] = invoice_url
    except Exception as e:
        print(f"WARNING: PDF Generation failed: {e}")
        invoice_url = None
    
    # 7. Create order record for customer portal
    await create_order({
        "customer_id": customer_id,
        "medicines": enriched_items,
        "total_amount": total,
        "bill_id": bill_id,
        "bill_mongo_id": new_bill["id"],
        "created_at": now,
    })

    # 8. Clear cart
    await remove_cart(customer_id)

    return {
        "message": "Bill generated successfully",
        "bill_id": bill_id,
        "subtotal": subtotal,
        "tax": tax,
        "discount": discount,
        "total": total,
        "customer_name": customer_name,
        "invoice_url": new_bill.get("invoice_url"),
        "bill_number": new_bill.get("bill_number")
    }
